[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.8"
evm_version = "shanghai"
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@chainlink/=lib/chainlink/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
