/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pyratzlabs API
 * Securd contracts
 * OpenAPI spec version: v1
 */
import type { Asset } from "./asset";

export interface BorrowBalance {
  token: Asset;
  balance: number;
}
