/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pyratzlabs API
 * Securd contracts
 * OpenAPI spec version: v1
 */

export interface BorrowerDataContract {
  /** Contract address, appliable to method calls */
  address?: string | null;
  supply?: number;
  l_token_supply_token_a?: string;
  l_token_supply_token_b?: string;
}
