/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pyratzlabs API
 * Securd contracts
 * OpenAPI spec version: v1
 */
import type { BorrowerDataContract } from "./borrowerDataContract";
import type { BorrowerModelContract } from "./borrowerModelContract";
import type { DexInfo } from "./dexInfo";
import type { LightLenderPool } from "./lightLenderPool";

export interface BorrowerPool {
  data_contract: BorrowerDataContract;
  model_contract: BorrowerModelContract;
  dex_info: DexInfo;
  readonly balanced_liquidation_threshold?: string;
  readonly unbalanced_liquidation_threshold?: string;
  oracle: string;
  readonly dex_apy?: string;
  lenderpool_set: LightLenderPool[];
}
