/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pyratzlabs API
 * Securd contracts
 * OpenAPI spec version: v1
 */

export interface LenderDeposit {
  balance?: number;
  readonly interest?: string;
}
