/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pyratzlabs API
 * Securd contracts
 * OpenAPI spec version: v1
 */

export interface LenderModelContract {
  /** Contract address, appliable to method calls */
  address?: string | null;
  interest_rate: number;
}
