/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pyratzlabs API
 * Securd contracts
 * OpenAPI spec version: v1
 */
import type { AssetAssetType } from "./assetAssetType";
import type { Fa12 } from "./fa12";
import type { Fa2Token } from "./fa2Token";

export interface Asset {
  asset_type?: AssetAssetType;
  asset_id: string;
  readonly xtz?: string;
  fa12?: Fa12;
  fa2?: Fa2Token;
}
