/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pyratzlabs API
 * Securd contracts
 * OpenAPI spec version: v1
 */
import type { DexApyHistoryReadInterpolation } from "./dexApyHistoryReadInterpolation";

export type DexApyHistoryReadParams = {
  /**
   * Interpolation frequency
   */
  interpolation?: DexApyHistoryReadInterpolation;
  /**
   * Date end timestamp
   */
  date_end?: string;
};
