/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pyratzlabs API
 * Securd contracts
 * OpenAPI spec version: v1
 */

export interface DexApyHistoryResponse {
  /** Timestamp */
  timestamp: string;
  /** Dex APY */
  dex_apy: number;
}
