/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pyratzlabs API
 * Securd contracts
 * OpenAPI spec version: v1
 */

export interface DTokenBalance {
  d_token_address: string;
  balance?: number;
}
