/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pyratzlabs API
 * Securd contracts
 * OpenAPI spec version: v1
 */

export interface LenderDataContract {
  /** Contract address, appliable to method calls */
  address?: string | null;
  d_token_price?: string;
  d_token_last_update_time: string;
  supply?: number;
  min_deposit_amount?: number;
  utilized_token?: number;
  l_token_price?: string;
  l_token_total_supply?: string;
  l_token_last_update_time?: string | null;
}
