/**
 * Generated by orval v6.16.0 🍺
 * Do not edit manually.
 * Pyratzlabs API
 * Securd contracts
 * OpenAPI spec version: v1
 */
import type { BorrowerDataContract } from "./borrowerDataContract";
import type { BorrowerModelContract } from "./borrowerModelContract";
import type { DexInfo } from "./dexInfo";

export interface LightBorrowerPool {
  data_contract: BorrowerDataContract;
  model_contract: BorrowerModelContract;
  dex_info: DexInfo;
}
